name: Deploy PulseScore
on: [push]
env:
  HOME: "/home/fantomasa"
  NVM_DIR: "/home/fantomasa/.nvm"
  PROJECT_DIR: "/home/fantomasa/docker/pulsescore_15"
  PROJECT_NAME: "pulsescore"
jobs:
  Auto-Deploy:
    runs-on: [self-hosted]
    steps:
      - name: Set up Node.js environment
        run: |
          source $NVM_DIR/nvm.sh
          nvm use node
      - name: Using versions and check DIRS
        run: |
          echo nvm: $(nvm -v)
          echo node: $(node -v)
          echo npm: $(npm -v)
          echo pm2: $(pm2 -v)
      - name: Pulling repo from Github
        run: |
          cd $PROJECT_DIR
          git pull
      - name: start container
        run: |
          docker-compose up -d --build

      # - name: Installing dependencies
      #   run: |
      #     cd $PROJECT_DIR
      #     npm install
      # - name: Build
      #   run: |
      #     cd $PROJECT_DIR
      #     npm run build
      # - name: Removing PM2 log
      #   run: pm2 flush
      # - name: Start app with PM2
      #   run: |
      #     cd $PROJECT_DIR
      #     pm2 stop $PROJECT_NAME || true  # Ignore errors if no PM2 processes exist
      #     pm2 start ecosystem.config.js --time  # --time option adds timestamps in PM2 logs
      #     pm2 save
      #     pm2 reset all
